-- MySQL Script generated by MySQL Workbench
-- 05/29/19 23:19:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema final_check
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema final_check
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smart_shop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `smart_shop` ;

-- -----------------------------------------------------
-- Table `final_check`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_shop`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_first_name` VARCHAR(50) NOT NULL,
  `us_last_name` VARCHAR(50) NOT NULL,
  `us_age` INT(2) NOT NULL,
  `us_gender` VARCHAR(6) NOT NULL,
  `us_contact_number` BIGINT(10) UNIQUE NOT NULL,
  `us_user_id` VARCHAR(15) NOT NULL,
  `us_password` VARCHAR(100) NOT NULL,
  `us_user_type` VARCHAR(1) NOT NULL,
  `us_status` VARCHAR(1) NOT NULL,
  `us_secret_question_one` VARCHAR(50) NOT NULL,
  `us_secret_Answer_one` VARCHAR(50) NOT NULL,
  `us_secret_question_two` VARCHAR(50) NOT NULL,
  `us_secret_Answer_two` VARCHAR(50) NOT NULL,
  `us_secret_question_three` VARCHAR(50) NOT NULL,
  `us_secret_Answer_three` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_shop`.`offer` (
  `of_id` INT NOT NULL AUTO_INCREMENT,
  `of_discount_percent` INT(11) NOT NULL,
  `of_date` DATE NOT NULL,
  `of_pt_code` INT(2) NOT NULL,
  PRIMARY KEY (`of_id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `smart_shop`.`product` (
  `pt_code` INT NOT NULL AUTO_INCREMENT,
  `pt_name` VARCHAR(50) NOT NULL,
  `pt_type` INT(2) NOT NULL,
  `pt_brand` VARCHAR(50) NOT NULL,
  `pt_quantity_type` BIGINT(10) NULL,
  `pt_rate_per_quantity` INT(15) NOT NULL,
  `pt_stock_count` INT(15) NOT NULL,
  `pt_add_date` DATE NOT NULL,
  `pt_aisle` VARCHAR(15) NOT NULL,
  `pt_shelf` VARCHAR(15) NOT NULL,
  `pt_date_of_manufacture` DATE NOT NULL,
  `pt_date_of_expiry` DATE NOT NULL,
  `pt_image` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`pt_code`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `smart_shop`.`bill` (
  `b_id` INT(11) NOT NULL AUTO_INCREMENT,
  `b_purchase_date` DATE NOT NULL,
  `b_total_amount` DECIMAL(8,2) NOT NULL,
  `b_discount_amount` DECIMAL(8,2) NOT NULL,
  `b_reward_points` INT(2) NOT NULL,
  `user_us_id` INT(11) NOT NULL,
  PRIMARY KEY (`b_id`),
  INDEX `fk_bill_user1_idx` (`user_us_id` ASC),
  CONSTRAINT `fk_bill_user1`
    FOREIGN KEY (`user_us_id`)
    REFERENCES `smart_shop`.`user` (`us_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart_shop`.`bill_details`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `smart_shop`.`bill_details` (
  `b_d_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_pt_code` INT(11) NOT NULL,
  `bill_b_id` INT(11) NOT NULL,
  `quantity` INT(11) default NULL,
  PRIMARY KEY (`b_d_id`),
  INDEX `fk_product_has_bill_bill1_idx` (`bill_b_id` ASC),
  INDEX `fk_product_has_bill_product1_idx` (`product_pt_code` ASC),
  CONSTRAINT `fk_product_has_bill_bill1`
    FOREIGN KEY (`bill_b_id`)
    REFERENCES `smart_shop`.`bill` (`b_id`),
  CONSTRAINT `fk_product_has_bill_product1`
    FOREIGN KEY (`product_pt_code`)
    REFERENCES `smart_shop`.`product` (`pt_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

insert into bill values(1, '2019-12-01',  165, 10, 2);

select * from bill where b_id=1;


insert into bill_details (product_pt_code, bill_b_id, quantity) values(16, 6, 0);
insert into bill_details (product_pt_code, bill_b_id, quantity) values(2, 1, 1);

select max(b_d_id) from bill_details;

select * from bill;
select * from bill_details;
desc bill;
desc bill_details;
select * from offer;

select sum(b_reward_points) from bill where user_us_id=2;


INSERT into `smart_shop`.`product` values (1,'Spoon',1,'Milton',1,'15','50','2019-03-15','1','1','2017-05-24','2020-04-09','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8KhvHoz1YF1iXQSHG2EPi0ZECPgLCAwBeyRDUVaXcnga1HfnN&s');
INSERT into `smart_shop`.`product` values (2,'Plate',1,'Milton',1,'150','50','2019-03-15','1','1','2017-05-24','2020-04-09','http://bollywoodparty.co.nz/wp-content/uploads/2018/07/WhitePorcelainDinnerPlatesS8SHS16.jpg');
INSERT into `smart_shop`.`product` values (3,'Bottle',1,'Milton',1,'50','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHG_9ZzpRacRJaVPBgv0o8AF5SMLNL-5d0lxvJp-eKvFXT_-XG7A&s');
INSERT into `smart_shop`.`product` values (4,'Tumbler',1,'Milton',1,'70','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://dwh39hsbrwe7m.cloudfront.net/media/catalog/product/cache/small_image/450x445/e528b4708ac73e10f87f72086ca7bb76/a/g/ageria_larah_borosil_opalglass_cup_fluted__6_pcs_220_ml_450x445.jpg');
INSERT into `smart_shop`.`product` values (5,'Pressure Cooker',1,'Milton',1,'1000','50','2019-03-15','2','1','2017-05-24','2020-04-09','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIDQiyPvkK3KQCbh-dyyNBlF4jQZsb-UdKz_8UsdlXRp9hkJuz1w&s');
INSERT into `smart_shop`.`product` values (6,'Garlic Bread',2,'Bakers Fresh',2,'70','20','2019-03-15','2','1','2017-05-24','2020-04-09','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7yeRushoqJbfyW___6-knXAg66ZNaSmPkbJQjTzNJmv7Er0U_&s');
INSERT into `smart_shop`.`product` values (7,'Fruit Jam',2,'Bakers Fresh',2,'50','30','2019-03-15','2','1','2017-05-24','2020-04-09','https://jstclick.com/image/cache/hindustan%20uniliver/kissan%20mix%20fruits-800x800.jpg');
INSERT into `smart_shop`.`product` values (8,'Cupcakes',2,'Bakers Fresh',2,'25','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://www.bbcgoodfood.com/sites/default/files/recipe-collections/collection-image/2013/05/vanilla_cupcakes.jpg');
INSERT into `smart_shop`.`product` values (9,'Cookies',2,'Bakers Fresh',2,'30','50','2019-03-15','2','1','2017-05-24','2020-04-09','https://mk0nationaltodayijln.kinstacdn.com/wp-content/uploads/2019/12/national-cookie-day-640x514.jpg');
INSERT into `smart_shop`.`product` values (10,'Homemade chocolate',2,'Bakers Fresh',2,'70','10','2019-03-15','2','1','2017-05-24','2020-04-09','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRULCYnzZRvfvGoYTlt_QecRCH1H-Wk4WO59kc7--rWJYho5Vmi&s');
INSERT into `smart_shop`.`product` values (11,'Orange',3,'Farm Fresh',3,'150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD4iPDkoNkvnlSbppIdJ1Pu51NF5A1FAXnHiWWiujt0P5_mLHReg&s');
INSERT into `smart_shop`.`product` values (12,'Apple',3,'Farm Fresh',3,'150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://media.gettyimages.com/photos/fresh-red-apples-on-white-background-picture-id183422512?s=612x612');
INSERT into `smart_shop`.`product` values (13,'Banana',3,'Farm Fresh',3,'150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://image.shutterstock.com/image-photo/bunch-bananas-isolated-on-white-260nw-1072013369.jpg');
INSERT into `smart_shop`.`product` values (14,'Dragon Fruit',3,'Farm Fresh',3,'150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTM8lVBshcjbvvaxLIhplUAniT0gb55bwevVEWp9MLGzT8_9haIQ&s');
INSERT into `smart_shop`.`product` values (15,'Papaya',3,'Farm Fresh',3,'150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://cdn.cdnparenting.com/articles/2018/12/27164729/1177502098-H.jpg');
INSERT into `smart_shop`.`product` values (16,'Popcorn',4,'Aci2',3,'150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://image.shutterstock.com/image-photo/popcorn-striped-bucket-isolated-on-260nw-175375529.jpg');

SELECT * FROM offer;
SELECT * FROM user ;
desc user;
SELECT * FROM product;
desc product;
select * from bill;
select * from bill_details;

select product_pt_code, sum(quantity)
from bill_details
group by product_pt_code
Order by sum(quantity) desc;

SELECT * FROM user where us_user_type='U';
select * from user where us_contact_number='9052601025';

SELECT * FROM product where pt_code not in (select pt_code from product INNER JOIN bill_Details ON (pt_code = product_pt_code) 
group by product_pt_code
Order by sum(quantity) desc);

select * from product INNER JOIN bill_Details ON (pt_code = product_pt_code) 
group by product_pt_code
Order by sum(quantity) desc;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
